        trigger:
        - main

        pool:
          name: local

        variables:
          imageName: 'pipelines-javascript-docker'
          tag: "latest"

        steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: app/Dockerfile
            containerRegistry: $(dockerRegistryServiceConnection)
            tags: |
              $(tag)